import type { TeamMember, Tenure } from "../types/team";

export const tenureFilters: Tenure[] = [
  "Current Tenure",
  "3rd Tenure",
  "2nd Tenure",
  "1st Tenure",
];

export const fullTeam: TeamMember[] = [
  /* ===================== CURRENT TENURE (2025 — 2026) — real roster ===================== */

  // Leadership
 
  {
    id: 101,
    name: "Rania Sadia Shah",
    role: "Leader",
    section: "Captain",
    tenure: "Current Tenure",
    image: "public/team/current_tenure/rania.webp",
    bio: "Hi everyone! I’m Rania, the AWS SBG Leader at MUET. I believe leadership is about creating space for others to learn, grow, and discover what they’re capable of. No matter where you’re starting from, you’re welcome here. Bring your curiosity, your ideas, and your willingness to learn. Let’s grow together, support one another, and make this community a place where everyone can thrive.",
    period: "2026 — 2027",
    email: "mailto:awsstudentbuilders@muet.edu.pk",
    github: "",
    linkedin: "https://www.linkedin.com/in/rania-shah-ba784a296",
  },
  {
    id: 102,
    name: "Jahanzeb Ansari",
    role: "Co-Lead",
    section: "Core Team",
     isCoLead: true,
    tenure: "Current Tenure",
    image: "public/team/current_tenure/jahanzaib.webp",
    bio: "I am Jahanzeb Ansari, currently serving as the President of this society.",
    github: "",
    linkedin: "",
  },
  {
    id: 103,
    name: "Humera Soomro",
    role: "Co-Lead",
    section: "Core Team",
     isCoLead: true,
    tenure: "Current Tenure",
    image: "public/team/current_tenure/humera.webp",
    bio: "I’m Humera, AWS Co-Lead for this tenure. I love taking initiative, bringing people together, and turning challenges into opportunities. For me, leadership means making sure we move forward together.",
    github: "https://github.com/HumeraSoomro",
    linkedin: "https://www.linkedin.com/in/humera-soomro-60724529",
  },

  // Operations & Technical
  {
    id: 104,
    name: "Faraz Siddiqui",
    role: "Operations & Technical",
    section: "Core Team",
    tenure: "Current Tenure",
       isHead: true,
 
    department: "Operations & Technical",
    image: "public/team/current_tenure/farazsiddiqui.webp",
    bio: "I’m Faraz Siddiqui, a final-year Software Engineering student at MUET. I’m a game developer interested in DevOps. I’m also involved in student societies and leadership activities, where I work on technical, management, and content projects.",
    github: "https://github.com/MuhammadFarazSiddiqui",
    linkedin: "https://www.linkedin.com/in/faraz-siddiqui-604b79340",
  },
  {
    id: 106,
    name: "Sayeel Abbas",
    role: "Operations & Technical",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Operations & Technical",
    image: "public/team/current_tenure/SYEDSAYEELABBAS.webp",
    bio: "I’m Syed Sayeel Abbas, a Software Engineering student at MUET. I’m passionate about software development, cloud computing, and AI. I enjoy building real-world projects, learning new technologies, and participating in technical activities and hackathons.",
    linkedin: "https://www.linkedin.com/in/syed-sayeel-abbas-a85a27327",
    github: "https://github.com/SyedSayeelAbbas",
  },
  {
    id: 107,
    name: "Muhammad Ahmed",
    role: "Operations & Technical",
    section: "Core Team",
  
    tenure: "Current Tenure",
    department: "Operations & Technical",
    image: "public/team/current_tenure/ahmed.webp",
    bio: "It's me Ahmed a software engineer by passion, a bug creator by accident, and a bug fixer by necessity.",
    github: "https://github.com/AhmedMemon7x  ",
    linkedin: "https://www.linkedin.com/in/muhammad-ahmed-memon-9819b9287",
  },
  
  {
    id: 105,
    name: "Muhammad Ubaid",
    role: "Operations & Technical",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Operations & Technical",
    image: "public/team/current_tenure/UbaidRaza.webp",
    bio: "I’m Ubaid Raza from MUET. I’m interested in technology and sports, and I enjoy learning by trying things out. I’m an aspiring app and web developer who likes exploring new technologies and meeting new people.",
    github: "https://github.com/ubaidraza-06",
    linkedin: "https://www.linkedin.com/in/m-ubaid-raza",
  },
  {
    id: 108,
    name: "Kumail Baloch",
    role: "Operations & Technical",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Operations & Technical",
    image: "public/team/current_tenure/kumail.jpg",
    bio: "I’m Kumail, an Artificial Intelligence student in my fifth semester, contributing to the Operations & Technical team.",
    github: "",
    linkedin: "https://www.linkedin.com/in/kumail-abbas-215722376",
  },

  // Designing Team
  {
    id: 109,
    name: "Maham Ali Lodhi",
    role: "Designing Team",
    section: "Core Team",
    tenure: "Current Tenure",
       isHead: true,
 
    department: "Designing Team",
    image: "public/team/current_tenure/maham.webp",
    bio: "I’m Maham, currently serving as Head of Design at AWS. I love learning new things, trying ideas, and turning them into something fun.",
    github: "",
    linkedin: "https://www.linkedin.com/in/maham-ali-lodhi-54109031b",
  },
  {
    id: 110,
    name: "Syed Izzat Fatima",
    role: "Designing Team",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Designing Team",
    image: "public/team/current_tenure/SyedaIzzatFatima.webp",
    bio: "",
    github: "",
    linkedin: "",
  },
  {
    id: 111,
    name: "Prithvi Raj",
    role: "Designing Team",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Designing Team",
    image: "public/team/current_tenure/Prithvi.webp",
    bio: "I enjoy music, YouTube, and nature. One of my dreams is to visit the Northern Areas.",
    github: "https://github.com/prithvifr",
    linkedin: "https://linkedin.com/in/prithvifr",
  },
  {
    id: 112,
    name: "Ezzah Ansari",
    role: "Designing Team",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Designing Team",
    image: "public/team/current_tenure/ezzahansari.webp",
    bio: "I’m Ezzah Ansari, a third-year Software Engineering student. I’m interested in web development, UI/UX, and graphic design. I love combining creativity and technology to build clean, modern digital experiences.",
    github: "",
    linkedin: "https://www.linkedin.com/in/ezzah-ansari",
  },

  // Content Management
  {
    id: 113,
    name: "Aliza Muhammad",
    role: "Content Management",
    section: "Core Team",
    tenure: "Current Tenure",
       isHead: true,
 
    department: "Content Management",
    image: "public/team/current_tenure/alizamuhammad.webp",
    bio: "I’m Aliza Muhammad, a final-year AI student and Head of Content at AWS. I enjoy movies, photography, and finding the right words to give content its own personality.",
    github: "",
    linkedin: "https://www.linkedin.com/in/aliza-muhammad-96460829a",
  },
  {
    id: 114,
    name: "Aneeqa Baig",
    role: "Content Management",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Content Management",
    image: "public/team/current_tenure/aneeqa.webp",
    bio: "I’m Aneeqa, a Software Engineering student with experience in content writing, editorial design, and social media management. I’m part of the AWS SBG MUET Content Management team. I also enjoy reading and painting.",
    github: "",
    linkedin: "https://www.linkedin.com/in/aneeqa-baig-96891b24a/",
  },
  {
    id: 115,
    name: "Anusha Talpur",
    role: "Content Management",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Content Management",
    image: "public/team/current_tenure/anusha.webp",
    bio: "I’m Anusha Talpur, a member of the AWS Content Management team. I have worked professionally in content for the past one and a half years. Writing is where my creativity shines, and I look forward to contributing to this tenure’s events.",
    github: "",
    linkedin: "https://www.linkedin.com/in/anusha-talpur-0a5907261",
  },
  {
    id: 116,
    name: "Muhammad Mahrus",
    role: "Content Management",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Content Management",
    image: "public/team/current_tenure/MahrusMemon.webp",
    bio: "I’m a member of the AWS Visuals Team, creating designs for our website and digital platforms. I enjoy combining creativity and technology to produce clean, impactful visuals.",
    github: "https://github.com/Muhammad-Mahrus",
    linkedin: "https://www.linkedin.com/in/mahrus-memon",
  },

  // Outreach & Marketing
  {
    id: 117,
    name: "Saria Nadeem",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "Current Tenure",
       isHead: true,
 
    department: "Outreach & Marketing",
    image: "public/team/current_tenure/sarianadeem.webp",
    bio: "I’m Saria Nadeem, Head of Marketing and Outreach at AWS SBG MUET. I enjoy connecting with people, creating meaningful engagement, and exploring creative marketing. I’m also interested in AI and Data Science.",
    github: "",
    linkedin: "https://linkedin.com/in/saria-nadeem-0124192b5",
  },

  {
    id: 119,
    name: "Maryam Rashid",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Outreach & Marketing",
    image: "public/team/current_tenure/maryamrashid.webp",
    bio: "I’m an Outreach & Marketing team member at AWS SBG. I’m passionate about growing student communities, coordinating technical workshops, and creating digital campaigns that connect students with AWS cloud technology.",
    github: "https://github.com/Maryamrashid0613",
    linkedin: "https://www.linkedin.com/in/maryam-rashid-083332297",
  },
  {
    id: 120,
    name: "Muhammad Saad",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Outreach & Marketing",
    image: "public/team/current_tenure/MuhammadSaadAbbasi.webp",
    bio: "I’m an Android developer, debate enthusiast, and literature lover.",
    github: "https://github.com/MuhammadSaadAbbasi",
    linkedin: "https://www.linkedin.com/in/muhammad-saad-abbasi-41767921b/",
  },
  {
    id: 118,
    name: "Hammad Masood",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Outreach & Marketing",
    image: "public/team/current_tenure/hammadmasood.webp",
    bio: "I’m Hammad from the Outreach & Marketing team. Outside club activities, I enjoy playing chess and building projects as a full-stack developer.",
    github: "https://github.com/hammad-masood26",
    linkedin: "https://www.linkedin.com/in/hammad-masood26",
  },
  // Visual Production
  {
    id: 121,
    name: "Aisha Idrees",
    role: "Visual Production",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Visual Production",
       isHead: true,
 
    image: "public/team/current_tenure/AyeshaIdrees.webp",
    bio: "I’m Aisha Idrees, Head of Visual Production at AWS MUET. What started as editing for fun grew into a passion for creating intentional, bold visual work. I’m excited to build a strong visual identity with the team.",
    github: "",
    linkedin: "https://www.linkedin.com/in/ayeshaidreeskhan",
  },
  {
    id: 122,
    name: "Shah Zaman Ali",
    role: "Visual Production",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Visual Production",
    image: "public/team/current_tenure/zaman.webp",
    bio: "I’m Shah Zaman Ali, a Cyber Security student at MUET interested in ethical hacking and CTFs. I also enjoy design, creating projects, and turning ideas into something real.",
    github: "",
    linkedin: "https://www.linkedin.com/in/shah-zaman-ali-2b1b3a321",
  },
  {
    id: 123,
    name: "Annah",
    role: "Visual Production",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Visual Production",
    image: "public/team/current_tenure/AinnaIbrahim.webp",
    bio: "",
    github: "",
    linkedin: "",
  },
  {
    id: 124,
    name: "Muhammad Dawood",
    role: "Visual Production",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Visual Production",
    image: "public/team/current_tenure/muhammaddawood.webp",
    bio: "I’m Muhammad Dawood. I turn ideas into visuals and stories into experiences. I enjoy creating, experimenting, learning new things, and finding ways to make ideas look better.",
    github: "",
    linkedin: "https://pk.linkedin.com/in/muhammad-dawood-026b323a2",
  },
  {
    id: 125,
    name: "Awais Ahmed",
    role: "Visual Production",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Visual Production",
    image: "public/team/current_tenure/awaisahmed.webp",
    bio: "I’m Awais Ahmed, a Cyber Security student and a video editor on the AWS Visual Production team.",
    github: "",
    linkedin: "https://www.linkedin.com/in/awais-ahmed-723a032b4",
  },

  /* ===================== 3RD TENURE (2024 — 2025) ===================== */
  {
    id: 7,
    name: "Captain Sarwat Aijaz",
    role: "Captain",
    section: "Captain",
    tenure: "3rd Tenure",
      image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Sarwat%20Aijaz.webp?updatedAt=1785579476187",
  
      bio: "Built upon the club’s success by launching the region’s first Student Community Day.",
    period: "2025 — 2026",
    linkedin: "#",
    instagram: "#",
  },
  /* ===================== 3RD TENURE (2025 — 2026) ===================== */
  {
    id: 7,
    name: "Zaeem Raza",
    role: "Vice Captain",
    section: "Core Team",
    tenure: "3rd Tenure",
    isCoLead:true,
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Zaeem%20Raza.webp?updatedAt=1785579475992",
    period: "2025 — 2026",
  },

  {
    id: 9,
    name: "Tayyaba Bhatti",
    role: "Vice Captain",
    section: "Core Team",
    tenure: "3rd Tenure",
    isCoLead:true,
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Tayyaba%20Bhatti%20.webp?updatedAt=1785579470034",
    period: "2025 — 2026",
  },
  {
    id: 10,
    name: "Jahanzaib Ansari",
    role: "Operations & Management",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Jahanzaib%20Ansari.webp?updatedAt=1785579468576",
    period: "2025 — 2026",
    isHead: true,
  },
  {
    id: 11,
    name: "Uroosham Memon",
    role: "Graphic Designer",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Uroosham%20Memon.webp?updatedAt=1785579474771",
    period: "2025 — 2026",
    isHead: true,
  },
  {
    id: 12,
    name: "Sahar Arif",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Sahar%20Arif.webp?updatedAt=1785579470079",
    period: "2025 — 2026",
    isHead: true,
  },
  {
    id: 13,
    name: "Apsara",
    role: "Visual Production",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Apsara.webp?updatedAt=1785579467515",
    period: "2025 — 2026",
    isHead: true,
  },
  {
    id: 14,
    name: "Faraz Siddiqui",
    role: "Content Management",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Faraz%20Siddiqui.webp?updatedAt=1785579466950",
    period: "2025 — 2026",
    isHead: true,
  },
  {
    id: 15,
    name: "Ikram Jamro",
    role: "Operations & Management",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Ikram%20Jamro.webp?updatedAt=1785579466540",
    period: "2025 — 2026",
  },
  {
    id: 16,
    name: "Hassan Jandan",
    role: "Graphic Designer",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Muhammad%20Hassan%20Jandan.webp?updatedAt=1785579467028",
    period: "2025 — 2026",
  },
  {
    id: 17,
    name: "Ahsan Abbas",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Ahsan%20Abbas%20Siddiqui.webp?updatedAt=1785579466261",
    period: "2025 — 2026",
  },
  {
    id: 18,
    name: "Hadisa Naqvi",
    role: "Visual Production",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Hadisa%20Naqvi.webp?updatedAt=1785579466302",
    period: "2025 — 2026",
  },
  {
    id: 19,
    name: "Aliza Muhammad",
    role: "Content Management",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Aliza%20Muhammad.webp?updatedAt=1785579465669",
    period: "2025 — 2026",
  },
  {
    id: 20,
    name: "Muzzamil Odho",
    role: "Operations & Management",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Muzzamil%20Odho.webp?updatedAt=1785579469505",
    period: "2025 — 2026",
  },
  {
    id: 21,
    name: "M. Umer",
    role: "Graphic Designer",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Muhammad%20Umer.webp?updatedAt=1785579466752",
    period: "2025 — 2026",
  },
  {
    id: 22,
    name: "Hadisa Syed",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Hadisa%20Fatima%20Syed.webp?updatedAt=1785579466997",
    period: "2025 — 2026",
  },
  {
    id: 23,
    name: "Raza Abbas",
    role: "Visual Production",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Raza%20Abbas.webp?updatedAt=1785579471697",
    period: "2025 — 2026",
  },
  {
    id: 24,
    name: "Areej Fatima",
    role: "Content Management",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Areej%20Fatima.webp?updatedAt=1785579466860",
    period: "2025 — 2026",
  },
  {
    id: 25,
    name: "Hanzlla Soomro",
    role: "Operations & Management",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Hanzlla%20Soomro.webp?updatedAt=1785579466619",
    period: "2025 — 2026",
  },
  {
    id: 26,
    name: "Aqsa Anwar",
    role: "Graphic Designer",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Aqsa%20Anwar.webp?updatedAt=1785579466820",
    period: "2025 — 2026",
  },
  {
    id: 27,
    name: "Sammar Safdar",
    role: "Visual Production",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Samar%20Safdar.webp?updatedAt=1785579477756",
    period: "2025 — 2026",
  },
  {
    id: 28,
    name: "Abdul Razzaque",
    role: "Content Management",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Abdul%20Razzaque.webp?updatedAt=1785579465486",
    period: "2025 — 2026",
  },
  {
    id: 29,
    name: "Zeeshan Talpur",
    role: "Operations & Management",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%203/Team%20Members/Zeeshan%20Talpur.webp?updatedAt=1785579471837",
    period: "2025 — 2026",
  },

  /* ===================== 2ND TENURE (2023 — 2024) ===================== */
  {
    id: 200,
    name: "Captain Jawad Soomro",
    role: "Captain",
    section: "Captain",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/jawad.webp?updatedAt=1785578948612",
    bio: "Took the club from a handful of members to a recognized MUET society.",
    period: "2024 — 2025",
    linkedin: "#",
    instagram: "#",
  },
 /* ===================== 2ND TENURE (2024 — 2025) ===================== */
  {
    id: 201,
    name: "Farah Ali",
    role: "Vice Captain",
    isCoLead:true,
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/farah.webp?updatedAt=1785578929460",
    period: "2024 — 2025",
  },
  {
    id: 202,
    name: "Musawwir",
    role: "Vice Captain",
    section: "Core Team",
    isCoLead:true,
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Mussawir.webp?updatedAt=1785578930795",
    period: "2024 — 2025",
  },
  {
    id: 203,
    name: "Anamta Batool",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Anamta%20batool.webp?updatedAt=1785578930690",
    period: "2024 — 2025",
  },
  {
    id: 204,
    name: "Yogeeta",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Yogeeta.webp?updatedAt=1785578931264",
    period: "2024 — 2025",
  },
  {
    id: 205,
    name: "Muhammad Ahsan",
    role: "Graphic Designer Head",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Ahsan.webp?updatedAt=1785578928812",
    period: "2024 — 2025",
    isHead: true,
  },
  {
    id: 206,
    name: "Rania",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Rania%20Sadia%20Shah.webp?updatedAt=1785578931583",
    period: "2024 — 2025",
  },
  {
    id: 207,
    name: "Rafay",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Rafay.webp?updatedAt=1785578932829",
    period: "2024 — 2025",
  },
  {
    id: 208,
    name: "Basit",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Abdul%20Basit.webp?updatedAt=1785578928794",
    period: "2024 — 2025",
  },
  {
    id: 209,
    name: "Hassan",
    role: "Media Production Head",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Hassan(2).webp?updatedAt=1785578931371",
    period: "2024 — 2025",
    isHead: true,
  },
  {
    id: 210,
    name: "Rida",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Rida.webp?updatedAt=1785578930748",
    period: "2024 — 2025",
  },
  {
    id: 211,
    name: "Insha Memon",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Insha%20Memon.webp?updatedAt=1785578930883",
    period: "2024 — 2025",
  },
  {
    id: 212,
    name: "Saria",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Saria.webp?updatedAt=1785578930782",
    period: "2024 — 2025",
  },
  {
    id: 213,
    name: "Taneesha",
    role: "Content Management Head",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "",
    period: "2024 — 2025",
    isHead: true,
  },
  {
    id: 214,
    name: "Azhar",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Azhar%20Ali.webp?updatedAt=1785578929275",
    period: "2024 — 2025",
  },
  {
    id: 215,
    name: "Asim",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Asim%20Raza.webp?updatedAt=1785578929564",
    period: "2024 — 2025",
  },
  {
    id: 216,
    name: "Mahad",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Mahad.webp?updatedAt=1785578949947",
    period: "2024 — 2025",
  },
  {
    id: 217,
    name: "Soorat Ali",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Soorat%20ALi.webp?updatedAt=1785578931246",
    period: "2024 — 2025",
  },
  {
    id: 218,
    name: "Shaheryar",
    role: "Technical Co-ordinator Head",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Shaheryar%20Ali.webp?updatedAt=1785578945453",
    period: "2024 — 2025",
    isHead: true,
  },
  {
    id: 219,
    name: "Summair",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "",
    period: "2024 — 2025",
  },
  {
    id: 220,
    name: "Ibrahim",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Muhammad%20Ibrahim.webp?updatedAt=1785578932177",
    period: "2024 — 2025",
  },
  {
    id: 221,
    name: "Sher M",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Sher%20Mohammad(1).webp?updatedAt=1785578930328",
    period: "2024 — 2025",
  },
  {
    id: 222,
    name: "Mudassir",
    role: "Team Member",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Mudassir.webp?updatedAt=1785578935672",
    period: "2024 — 2025",
  },
  {
    id: 223,
    name: "Shakiba",
    role: "Py/Ootreach Co-ordinator Head",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%202/Team%20Members/Shakiba%20Ansari.webp?updatedAt=1785578930045",
    period: "2024 — 2025",
    isHead: true,
  },

  /* ===================== 1ST TENURE (2023, founding) ===================== */
  {
    id: 14,
    name: "Captain Munsif Raza",
    role: "Founding Captain",
    section: "Captain",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/Captain%20Munsif%20Raza.png?updatedAt=1785578959173",
    bio: "Founded AWS Cloud Club MUET and laid the groundwork for everything that followed.",
    period: "2023-2024",
    linkedin: "#",
    instagram: "#",
  },
/* ===================== 1ST TENURE (2023 — 2024) ===================== */

  {
    id: 301,
    name: "Mehar Ali Shah",
    role: "Vice Captain",
    isCoLead:true,
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Meher.webp?updatedAt=1785578937453",
    period: "2023 — 2024",
  },
  {
    id: 302,
    name: "Jawad Soomro",
    role: "Technical Coordinator",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Jawad.webp?updatedAt=1785578942030",
    period: "2023 — 2024",
  },
  {
    id: 303,
    name: "Zohaib Ali Thaheem",
    role: "Technical Coordinator",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Zohaib.webp?updatedAt=1785578938737",
    period: "2023 — 2024",
  },
  {
    id: 304,
    name: "Pawang Rai Lohana",
    role: "Technical Coordinator",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Pawang.webp?updatedAt=1785578939958",
    period: "2023 — 2024",
  },
  {
    id: 305,
    name: "Aryan Memon",
    role: "Technical Coordinator",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Aryan.webp?updatedAt=1785578947885",
    period: "2023 — 2024",
  },
  {
    id: 306,
    name: "Saddar udin Babar",
    role: "Technical Coordinator",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Saddar.webp?updatedAt=1785578947505",
    period: "2023 — 2024",
  },
  {
    id: 307,
    name: "Fida Hussain",
    role: "Video Editor",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Fida.webp?updatedAt=1785578941900",
    period: "2023 — 2024",
  },
  {
    id: 308,
    name: "Areeba Khan",
    role: "Photographer/Videographer",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Areeba.webp?updatedAt=1785578937407",
    period: "2023 — 2024",
  },
  {
    id: 309,
    name: "Zaeem Raza",
    role: "Video Editor",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Zaeem.webp?updatedAt=1785578938252",
    period: "2023 — 2024",
  },
  {
    id: 310,
    name: "Anza Aleem",
    role: "PR and Outreach Coordinator",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Anza.webp?updatedAt=1785578936437",
    period: "2023 — 2024",
  },
  {
    id: 311,
    name: "Anas Naeem",
    role: "PR and Outreach Coordinator",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Anas.webp?updatedAt=1785578934581",
    period: "2023 — 2024",
  },
  {
    id: 312,
    name: "Shigraf Khalid",
    role: "Social Media Manager",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Shigraf.webp?updatedAt=1785578939997",
    period: "2023 — 2024",
  },
  {
    id: 313,
    name: "Syeda Reeba Zaidi",
    role: "Social Media Manager",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Reeba.webp?updatedAt=1785578939414",
    period: "2023 — 2024",
  },
  {
    id: 314,
    name: "Mussawir",
    role: "Content Writer",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Mussawir.webp?updatedAt=1785578938718",
    period: "2023 — 2024",
  },
  {
    id: 315,
    name: "Sarwat Aijaz",
    role: "Content Writer",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Sarwat.webp?updatedAt=1785578943728",
    period: "2023 — 2024",
  },
  {
    id: 316,
    name: "Muhammad Ahsan",
    role: "Graphics Designer",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "https://ik.imagekit.io/st2pn8py0c/AWSX/Tenure%201/MunsifTeam/Ahsan.webp?updatedAt=1785578933652",
    period: "2023 — 2024",
  },
];