import type { TeamMember, Tenure } from "../types/team";

export const tenureFilters: Tenure[] = [
  "Current Tenure",
  "3rd Tenure",
  "2nd Tenure",
  "1st Tenure",
];

export const fullTeam: TeamMember[] = [
  /* ===================== CURRENT TENURE (2025 — 2026) — real roster ===================== */

  // Leadership
  {
    id: 101,
    name: "Rania Sadia Shah",
    role: "Leader",
    section: "Captain",
    tenure: "Current Tenure",
    image: "/team/current/leader.webp",
    bio: "Leads the AWS Student Builder Club's vision, partnerships and overall direction.",
    period: "2025 — 2026",
    linkedin: "#",
    instagram: "#",
    github: "#",
    email: "mailto:lead@awsclub.muet.edu.pk",
  },
  {
    id: 102,
    name: "Jahanzeb Ansari",
    role: "Co-Lead",
    section: "Core Team",
    tenure: "Current Tenure",
    isCoLead: true,
    image: "/team/current/co-lead-jahanzeb.webp",
    bio: "Supports club leadership across strategy and cross-team coordination.",
    linkedin: "#",
    instagram: "#",
  },
  {
    id: 103,
    name: "Humera Soomro",
    role: "Co-Lead",
    section: "Core Team",
    tenure: "Current Tenure",
    isCoLead: true,
    image: "/team/current/co-lead-humera.webp",
    bio: "Supports club leadership across strategy and cross-team coordination.",
    linkedin: "#",
    instagram: "#",
  },

  // Operations & Technical
  {
    id: 104,
    name: "Faraz Siddiqui",
    role: "Operations & Technical",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Operations & Technical",
    isHead: true,
    image: "/team/current/faraz-siddiqui.webp",
    bio: "Heads the Operations & Technical team, overseeing workshops and technical infrastructure.",
    github: "#",
  },
  {
    id: 105,
    name: "Muhammad Ubaid",
    role: "Operations & Technical",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Operations & Technical",
    image: "/team/current/muhammad-ubaid.webp",
    bio: "Contributes to the Operations & Technical team, supporting workshops and technical delivery.",
  },
  {
    id: 106,
    name: "Sayeel Abbas",
    role: "Operations & Technical",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Operations & Technical",
    image: "/team/current/sayeel-abbas.webp",
    bio: "Contributes to the Operations & Technical team, supporting workshops and technical delivery.",
  },
  {
    id: 107,
    name: "Muhammad Ahmed",
    role: "Operations & Technical",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Operations & Technical",
    image: "/team/current/muhammad-ahmed.webp",
    bio: "Contributes to the Operations & Technical team, supporting workshops and technical delivery.",
  },
  {
    id: 108,
    name: "Kumail Baloch",
    role: "Operations & Technical",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Operations & Technical",
    image: "/team/current/kumail-baloch.webp",
    bio: "Contributes to the Operations & Technical team, supporting workshops and technical delivery.",
  },

  // Designing Team
  {
    id: 109,
    name: "Maham Ali Lodhi",
    role: "Designing Team",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Designing Team",
    isHead: true,
    image: "/team/current/maham-ali-lodhi.webp",
    bio: "Heads the Designing Team, shaping the club's visual identity and creative direction.",
    instagram: "#",
  },
  {
    id: 110,
    name: "Syed Izzat Fatima",
    role: "Designing Team",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Designing Team",
    image: "/team/current/syed-izzat-fatima.webp",
    bio: "Contributes to the Designing Team, crafting visuals and design assets for the club.",
  },
  {
    id: 111,
    name: "Prithvi Raj",
    role: "Designing Team",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Designing Team",
    image: "/team/current/prithvi-raj.webp",
    bio: "Contributes to the Designing Team, crafting visuals and design assets for the club.",
  },
  {
    id: 112,
    name: "Ezzah Ansari",
    role: "Designing Team",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Designing Team",
    image: "/team/current/ezzah-ansari.webp",
    bio: "Contributes to the Designing Team, crafting visuals and design assets for the club.",
  },

  // Content Management
  {
    id: 113,
    name: "Aliza Muhammad",
    role: "Content Management",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Content Management",
    isHead: true,
    image: "/team/current/aliza-muhammad.webp",
    bio: "Heads Content Management, overseeing the club's messaging and written content.",
    linkedin: "#",
  },
  {
    id: 114,
    name: "Aneeqa Baig",
    role: "Content Management",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Content Management",
    image: "/team/current/aneeqa-baig.webp",
    bio: "Contributes to Content Management, writing and organizing content for the club.",
  },
  {
    id: 115,
    name: "Anusha Talpur",
    role: "Content Management",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Content Management",
    image: "/team/current/anusha-talpur.webp",
    bio: "Contributes to Content Management, writing and organizing content for the club.",
  },
  {
    id: 116,
    name: "Muhammad Mahrus",
    role: "Content Management",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Content Management",
    image: "/team/current/muhammad-mahrus.webp",
    bio: "Contributes to Content Management, writing and organizing content for the club.",
  },

  // Outreach & Marketing
  {
    id: 117,
    name: "Saria Nadeem",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Outreach & Marketing",
    isHead: true,
    image: "/team/current/saria-nadeem.webp",
    bio: "Heads Outreach & Marketing, driving the club's promotion and community reach.",
    instagram: "#",
  },
  {
    id: 118,
    name: "Hammad Masood",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Outreach & Marketing",
    image: "/team/current/hammad-masood.webp",
    bio: "Contributes to Outreach & Marketing, helping grow the club's community presence.",
  },
  {
    id: 119,
    name: "Maryam Rashid",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Outreach & Marketing",
    image: "/team/current/maryam-rashid.webp",
    bio: "Contributes to Outreach & Marketing, helping grow the club's community presence.",
  },
  {
    id: 120,
    name: "Muhammad Saad",
    role: "Outreach & Marketing",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Outreach & Marketing",
    image: "/team/current/muhammad-saad.webp",
    bio: "Contributes to Outreach & Marketing, helping grow the club's community presence.",
  },

  // Visual Production
  {
    id: 121,
    name: "Aisha Idrees",
    role: "Visual Production",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Visual Production",
    isHead: true,
    image: "/team/current/aisha-idrees.webp",
    bio: "Heads Visual Production, leading photography and video coverage of club events.",
    instagram: "#",
  },
  {
    id: 122,
    name: "Shah Zaman Ali",
    role: "Visual Production",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Visual Production",
    image: "/team/current/shah-zaman-ali.webp",
    bio: "Contributes to Visual Production, capturing and producing visual content for events.",
  },
  {
    id: 123,
    name: "Annah",
    role: "Visual Production",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Visual Production",
    image: "/team/current/annah.webp",
    bio: "Contributes to Visual Production, capturing and producing visual content for events.",
  },
  {
    id: 124,
    name: "Muhammad Dawood",
    role: "Visual Production",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Visual Production",
    image: "/team/current/muhammad-dawood.webp",
    bio: "Contributes to Visual Production, capturing and producing visual content for events.",
  },
  {
    id: 125,
    name: "Awais Ahmed",
    role: "Visual Production",
    section: "Core Team",
    tenure: "Current Tenure",
    department: "Visual Production",
    image: "/team/current/awais-ahmed.webp",
    bio: "Contributes to Visual Production, capturing and producing visual content for events.",
  },

  /* ===================== 3RD TENURE (2024 — 2025) ===================== */
  {
    id: 7,
    name: "Zainab Sheikh",
    role: "Captain",
    section: "Captain",
    tenure: "3rd Tenure",
    image: "/team/tenure-3/captain.webp",
    bio: "Grew the club's certification track and launched the first inter-university hackathon.",
    period: "2024 — 2025",
    linkedin: "#",
    instagram: "#",
  },
  {
    id: 8,
    name: "Danish Korai",
    role: "Vice Captain",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "/team/tenure-3/vice-captain.webp",
    bio: "Coordinated cross-department logistics for every major event.",
    period: "2024 — 2025",
    linkedin: "#",
    instagram: "#",
  },
  {
    id: 9,
    name: "Mahnoor Abbasi",
    role: "Technical Lead",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "/team/tenure-3/technical-lead.webp",
    bio: "Ran the club's first hands-on Solutions Architect prep bootcamp.",
    github: "#",
  },
  {
    id: 10,
    name: "Faizan Larik",
    role: "Design Lead",
    section: "Core Team",
    tenure: "3rd Tenure",
    image: "/team/tenure-3/design-lead.webp",
    bio: "Rebuilt the club's brand identity and social media presence.",
    github: "#",
  },

  /* ===================== 2ND TENURE (2023 — 2024) ===================== */
  {
    id: 11,
    name: "Rohail Junejo",
    role: "Captain",
    section: "Captain",
    tenure: "2nd Tenure",
    image: "/team/tenure-2/captain.webp",
    bio: "Took the club from a handful of members to a recognized MUET society.",
    period: "2023 — 2024",
    linkedin: "#",
    instagram: "#",
  },
  {
    id: 12,
    name: "Sadia Chandio",
    role: "General Secretary",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "/team/tenure-2/secretary.webp",
    bio: "Set up the club's first documentation and onboarding process.",
    email: "mailto:sadia@example.com",
  },
  {
    id: 13,
    name: "Owais Bhutto",
    role: "Events Lead",
    section: "Core Team",
    tenure: "2nd Tenure",
    image: "/team/tenure-2/events-lead.webp",
    bio: "Organized the club's first AWS cloud workshop series.",
    linkedin: "#",
    instagram: "#",
  },

  /* ===================== 1ST TENURE (2023, founding) ===================== */
  {
    id: 14,
    name: "Faizan Qureshi",
    role: "Founding Captain",
    section: "Captain",
    tenure: "1st Tenure",
    image: "/team/tenure-1/captain.webp",
    bio: "Founded AWS Cloud Club MUET and laid the groundwork for everything that followed.",
    period: "2023",
    linkedin: "#",
    instagram: "#",
  },
  {
    id: 15,
    name: "Anum Rajput",
    role: "Founding Member",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "/team/tenure-1/founding-member-1.webp",
    bio: "Helped recruit the club's first 50 members.",
    linkedin: "#",
    instagram: "#",
  },
  {
    id: 16,
    name: "Kabeer Panhwar",
    role: "Founding Member",
    section: "Core Team",
    tenure: "1st Tenure",
    image: "/team/tenure-1/founding-member-2.webp",
    bio: "Ran the club's very first orientation session.",
    github: "#",
  },
];